import { Injectable, signal } from '@angular/core';
import {
  TransactionListItem,
  DemoScenario,
  NetworkNode,
  NetworkEdge,
  AuditRecord,
} from '../models/risk.models';

@Injectable({
  providedIn: 'root',
})
export class TransactionService {
  // Pre-curated realistic transactions from Phase 3/5 benchmarks
  private readonly mockTransactions: TransactionListItem[] = [
    {
      transaction_id: 'tx_0027436',
      timestamp: '2026-03-16T03:14:22Z',
      amount: 249.99,
      product_category: 'electronics',
      risk_score: 1.0000,
      risk_level: 'HIGH',
      decision: 'BLOCK',
      primary_reason: 'NEW_ACCOUNT + GRAPH_CONNECTED_USERS',
      user_id: 'usr_004812',
      is_promo_used: 1,
      connected_users: 8,
      features: {
        amount: 249.99,
        product_category: 'electronics',
        is_promo_used: 1,
        hour_of_day: 3,
        day_of_week: 2,
        is_weekend: 0,
        billing_shipping_match: 0,
        account_age_days: 0.45,
        email_domain: 'tempmail.org',
        user_tx_count_1h: 2,
        user_tx_count_24h: 4,
        user_tx_count_7d: 4,
        user_historical_tx_count: 1,
        user_historical_mean_amount: 249.99,
        user_historical_std_amount: 0.0,
        amount_to_user_mean_ratio: 1.0,
        user_promo_rate: 1.0,
        user_unique_device_count: 1,
        user_unique_ip_count: 2,
        user_unique_payment_count: 1,
        user_unique_address_count: 1,
        device_prior_user_count: 7,
        ip_prior_user_count: 4,
        payment_prior_user_count: 6,
        shipping_address_prior_user_count: 1,
        billing_address_prior_user_count: 0,
        max_shared_entity_user_count: 7,
        number_of_prior_connected_users: 8,
        shared_entity_types_count: 3,
        connected_component_user_count: 8,
        connected_component_total_nodes: 14,
        connected_component_edge_count: 22,
        connected_component_density: 0.2418,
      },
    },
    {
      transaction_id: 'tx_0027410',
      timestamp: '2026-03-16T02:48:10Z',
      amount: 189.50,
      product_category: 'electronics',
      risk_score: 0.9998,
      risk_level: 'HIGH',
      decision: 'BLOCK',
      primary_reason: 'GRAPH_SHARED_DEVICE + GRAPH_SHARED_PAYMENT',
      user_id: 'usr_004809',
      is_promo_used: 1,
      connected_users: 7,
      features: {
        amount: 189.50,
        product_category: 'electronics',
        is_promo_used: 1,
        hour_of_day: 2,
        day_of_week: 2,
        is_weekend: 0,
        billing_shipping_match: 0,
        account_age_days: 0.82,
        email_domain: 'trashmail.com',
        user_tx_count_1h: 1,
        user_tx_count_24h: 3,
        user_tx_count_7d: 3,
        user_historical_tx_count: 2,
        user_historical_mean_amount: 189.50,
        user_historical_std_amount: 0.0,
        amount_to_user_mean_ratio: 1.0,
        user_promo_rate: 1.0,
        user_unique_device_count: 1,
        user_unique_ip_count: 1,
        user_unique_payment_count: 1,
        user_unique_address_count: 1,
        device_prior_user_count: 6,
        ip_prior_user_count: 4,
        payment_prior_user_count: 5,
        shipping_address_prior_user_count: 1,
        billing_address_prior_user_count: 0,
        max_shared_entity_user_count: 6,
        number_of_prior_connected_users: 7,
        shared_entity_types_count: 3,
        connected_component_user_count: 8,
        connected_component_total_nodes: 14,
        connected_component_edge_count: 22,
        connected_component_density: 0.2418,
      },
    },
    {
      transaction_id: 'tx_0024439',
      timestamp: '2026-03-08T18:22:45Z',
      amount: 64.20,
      product_category: 'home_goods',
      risk_score: 0.0002,
      risk_level: 'LOW',
      decision: 'APPROVE',
      primary_reason: 'GRAPH_SHARED_ADDRESS (Legitimate Household)',
      user_id: 'usr_002104',
      is_promo_used: 0,
      connected_users: 2,
      features: {
        amount: 64.20,
        product_category: 'home_goods',
        is_promo_used: 0,
        hour_of_day: 18,
        day_of_week: 1,
        is_weekend: 0,
        billing_shipping_match: 1,
        account_age_days: 74.5,
        email_domain: 'gmail.com',
        user_tx_count_1h: 0,
        user_tx_count_24h: 0,
        user_tx_count_7d: 1,
        user_historical_tx_count: 6,
        user_historical_mean_amount: 58.10,
        user_historical_std_amount: 12.4,
        amount_to_user_mean_ratio: 1.1,
        user_promo_rate: 0.16,
        user_unique_device_count: 1,
        user_unique_ip_count: 1,
        user_unique_payment_count: 1,
        user_unique_address_count: 1,
        device_prior_user_count: 1,
        ip_prior_user_count: 2,
        payment_prior_user_count: 2,
        shipping_address_prior_user_count: 2,
        billing_address_prior_user_count: 2,
        max_shared_entity_user_count: 2,
        number_of_prior_connected_users: 2,
        shared_entity_types_count: 2,
        connected_component_user_count: 2,
        connected_component_total_nodes: 5,
        connected_component_edge_count: 4,
        connected_component_density: 0.40,
      },
    },
    {
      transaction_id: 'tx_0024882',
      timestamp: '2026-03-09T14:15:30Z',
      amount: 112.00,
      product_category: 'apparel',
      risk_score: 0.0001,
      risk_level: 'LOW',
      decision: 'APPROVE',
      primary_reason: 'GRAPH_CONNECTED_USERS (Corporate Egress IP)',
      user_id: 'usr_003115',
      is_promo_used: 0,
      connected_users: 5,
      features: {
        amount: 112.00,
        product_category: 'apparel',
        is_promo_used: 0,
        hour_of_day: 14,
        day_of_week: 2,
        is_weekend: 0,
        billing_shipping_match: 1,
        account_age_days: 112.0,
        email_domain: 'corporate.com',
        user_tx_count_1h: 0,
        user_tx_count_24h: 1,
        user_tx_count_7d: 2,
        user_historical_tx_count: 12,
        user_historical_mean_amount: 105.00,
        user_historical_std_amount: 22.1,
        amount_to_user_mean_ratio: 1.06,
        user_promo_rate: 0.08,
        user_unique_device_count: 1,
        user_unique_ip_count: 1,
        user_unique_payment_count: 1,
        user_unique_address_count: 1,
        device_prior_user_count: 1,
        ip_prior_user_count: 5,
        payment_prior_user_count: 1,
        shipping_address_prior_user_count: 1,
        billing_address_prior_user_count: 1,
        max_shared_entity_user_count: 5,
        number_of_prior_connected_users: 5,
        shared_entity_types_count: 1,
        connected_component_user_count: 5,
        connected_component_total_nodes: 9,
        connected_component_edge_count: 8,
        connected_component_density: 0.22,
      },
    },
    {
      transaction_id: 'tx_0012427',
      timestamp: '2026-03-01T11:05:12Z',
      amount: 45.90,
      product_category: 'groceries',
      risk_score: 0.0001,
      risk_level: 'LOW',
      decision: 'APPROVE',
      primary_reason: 'LOW_RISK_ESTABLISHED_ACCOUNT',
      user_id: 'usr_000412',
      is_promo_used: 0,
      connected_users: 0,
      features: {
        amount: 45.90,
        product_category: 'groceries',
        is_promo_used: 0,
        hour_of_day: 11,
        day_of_week: 0,
        is_weekend: 1,
        billing_shipping_match: 1,
        account_age_days: 140.2,
        email_domain: 'gmail.com',
        user_tx_count_1h: 0,
        user_tx_count_24h: 0,
        user_tx_count_7d: 1,
        user_historical_tx_count: 18,
        user_historical_mean_amount: 42.50,
        user_historical_std_amount: 8.9,
        amount_to_user_mean_ratio: 1.08,
        user_promo_rate: 0.05,
        user_unique_device_count: 1,
        user_unique_ip_count: 1,
        user_unique_payment_count: 1,
        user_unique_address_count: 1,
        device_prior_user_count: 1,
        ip_prior_user_count: 1,
        payment_prior_user_count: 1,
        shipping_address_prior_user_count: 1,
        billing_address_prior_user_count: 1,
        max_shared_entity_user_count: 1,
        number_of_prior_connected_users: 0,
        shared_entity_types_count: 0,
        connected_component_user_count: 1,
        connected_component_total_nodes: 4,
        connected_component_edge_count: 3,
        connected_component_density: 0.50,
      },
    },
    {
      transaction_id: 'tx_0014738',
      timestamp: '2026-03-02T19:40:15Z',
      amount: 135.00,
      product_category: 'beauty',
      risk_score: 0.6210,
      risk_level: 'MEDIUM',
      decision: 'REVIEW',
      primary_reason: 'NEW_ACCOUNT + PROMO_ACTIVITY',
      user_id: 'usr_003890',
      is_promo_used: 1,
      connected_users: 1,
      features: {
        amount: 135.00,
        product_category: 'beauty',
        is_promo_used: 1,
        hour_of_day: 19,
        day_of_week: 1,
        is_weekend: 0,
        billing_shipping_match: 1,
        account_age_days: 1.8,
        email_domain: 'yahoo.com',
        user_tx_count_1h: 0,
        user_tx_count_24h: 1,
        user_tx_count_7d: 1,
        user_historical_tx_count: 1,
        user_historical_mean_amount: 135.00,
        user_historical_std_amount: 0.0,
        amount_to_user_mean_ratio: 1.0,
        user_promo_rate: 1.0,
        user_unique_device_count: 1,
        user_unique_ip_count: 1,
        user_unique_payment_count: 1,
        user_unique_address_count: 1,
        device_prior_user_count: 1,
        ip_prior_user_count: 1,
        payment_prior_user_count: 1,
        shipping_address_prior_user_count: 1,
        billing_address_prior_user_count: 1,
        max_shared_entity_user_count: 1,
        number_of_prior_connected_users: 1,
        shared_entity_types_count: 0,
        connected_component_user_count: 1,
        connected_component_total_nodes: 4,
        connected_component_edge_count: 3,
        connected_component_density: 0.50,
      },
    },
  ];

  // Curated 5 Demo Scenarios for Live Evaluation
  readonly demoScenarios: DemoScenario[] = [
    {
      id: 'case_ring',
      title: 'Coordinated Abuse Ring',
      category: 'HIGH_RISK_SYNDICATE',
      description: 'Multi-account card-testing mesh rotating through a shared device and disposable emails.',
      expectedDecision: 'BLOCK',
      expectedLevel: 'HIGH',
      keySignal: '7 Device Accounts + 8 Connected Users + 0.45d Account Age',
      transaction_id: 'tx_demo_ring_001',
      features: {
        amount: 249.99,
        product_category: 'electronics',
        is_promo_used: 1,
        hour_of_day: 3,
        day_of_week: 2,
        is_weekend: 0,
        billing_shipping_match: 0,
        account_age_days: 0.45,
        email_domain: 'tempmail.org',
        user_tx_count_1h: 2,
        user_tx_count_24h: 4,
        user_tx_count_7d: 4,
        user_historical_tx_count: 1,
        user_historical_mean_amount: 249.99,
        user_historical_std_amount: 0.0,
        amount_to_user_mean_ratio: 1.0,
        user_promo_rate: 1.0,
        user_unique_device_count: 1,
        user_unique_ip_count: 2,
        user_unique_payment_count: 1,
        user_unique_address_count: 1,
        device_prior_user_count: 7,
        ip_prior_user_count: 4,
        payment_prior_user_count: 6,
        shipping_address_prior_user_count: 1,
        billing_address_prior_user_count: 0,
        max_shared_entity_user_count: 7,
        number_of_prior_connected_users: 8,
        shared_entity_types_count: 3,
        connected_component_user_count: 8,
        connected_component_total_nodes: 14,
        connected_component_edge_count: 22,
        connected_component_density: 0.2418,
      },
    },
    {
      id: 'case_household',
      title: 'Family Household',
      category: 'BENIGN_SHARED_INFRASTRUCTURE',
      description: 'Family members sharing a physical address and home Wi-Fi with distinct devices and cards.',
      expectedDecision: 'APPROVE',
      expectedLevel: 'LOW',
      keySignal: 'Shared address + Shared IP, but established account tenure (>70d)',
      transaction_id: 'tx_demo_household_002',
      features: {
        amount: 64.20,
        product_category: 'home_goods',
        is_promo_used: 0,
        hour_of_day: 18,
        day_of_week: 1,
        is_weekend: 0,
        billing_shipping_match: 1,
        account_age_days: 74.5,
        email_domain: 'gmail.com',
        user_tx_count_1h: 0,
        user_tx_count_24h: 0,
        user_tx_count_7d: 1,
        user_historical_tx_count: 6,
        user_historical_mean_amount: 58.10,
        user_historical_std_amount: 12.4,
        amount_to_user_mean_ratio: 1.1,
        user_promo_rate: 0.16,
        user_unique_device_count: 1,
        user_unique_ip_count: 1,
        user_unique_payment_count: 1,
        user_unique_address_count: 1,
        device_prior_user_count: 1,
        ip_prior_user_count: 2,
        payment_prior_user_count: 2,
        shipping_address_prior_user_count: 2,
        billing_address_prior_user_count: 2,
        max_shared_entity_user_count: 2,
        number_of_prior_connected_users: 2,
        shared_entity_types_count: 2,
        connected_component_user_count: 2,
        connected_component_total_nodes: 5,
        connected_component_edge_count: 4,
        connected_component_density: 0.40,
      },
    },
    {
      id: 'case_corporate',
      title: 'Corporate Office',
      category: 'BENIGN_SHARED_IP',
      description: 'Colleagues placing apparel orders from a shared enterprise NAT egress gateway IP.',
      expectedDecision: 'APPROVE',
      expectedLevel: 'LOW',
      keySignal: 'Shared corporate IP, unique cards/devices and long user history',
      transaction_id: 'tx_demo_corp_003',
      features: {
        amount: 112.00,
        product_category: 'apparel',
        is_promo_used: 0,
        hour_of_day: 14,
        day_of_week: 2,
        is_weekend: 0,
        billing_shipping_match: 1,
        account_age_days: 112.0,
        email_domain: 'corporate.com',
        user_tx_count_1h: 0,
        user_tx_count_24h: 1,
        user_tx_count_7d: 2,
        user_historical_tx_count: 12,
        user_historical_mean_amount: 105.00,
        user_historical_std_amount: 22.1,
        amount_to_user_mean_ratio: 1.06,
        user_promo_rate: 0.08,
        user_unique_device_count: 1,
        user_unique_ip_count: 1,
        user_unique_payment_count: 1,
        user_unique_address_count: 1,
        device_prior_user_count: 1,
        ip_prior_user_count: 5,
        payment_prior_user_count: 1,
        shipping_address_prior_user_count: 1,
        billing_address_prior_user_count: 1,
        max_shared_entity_user_count: 5,
        number_of_prior_connected_users: 5,
        shared_entity_types_count: 1,
        connected_component_user_count: 5,
        connected_component_total_nodes: 9,
        connected_component_edge_count: 8,
        connected_component_density: 0.22,
      },
    },
    {
      id: 'case_isolated',
      title: 'Established Shopper',
      category: 'BENIGN_ISOLATED',
      description: 'Standard repeat consumer ordering groceries with zero entity sharing.',
      expectedDecision: 'APPROVE',
      expectedLevel: 'LOW',
      keySignal: 'Account age >140d, zero graph connectivity, 18 prior transactions',
      transaction_id: 'tx_demo_shopper_004',
      features: {
        amount: 45.90,
        product_category: 'groceries',
        is_promo_used: 0,
        hour_of_day: 11,
        day_of_week: 0,
        is_weekend: 1,
        billing_shipping_match: 1,
        account_age_days: 140.2,
        email_domain: 'gmail.com',
        user_tx_count_1h: 0,
        user_tx_count_24h: 0,
        user_tx_count_7d: 1,
        user_historical_tx_count: 18,
        user_historical_mean_amount: 42.50,
        user_historical_std_amount: 8.9,
        amount_to_user_mean_ratio: 1.08,
        user_promo_rate: 0.05,
        user_unique_device_count: 1,
        user_unique_ip_count: 1,
        user_unique_payment_count: 1,
        user_unique_address_count: 1,
        device_prior_user_count: 1,
        ip_prior_user_count: 1,
        payment_prior_user_count: 1,
        shipping_address_prior_user_count: 1,
        billing_address_prior_user_count: 1,
        max_shared_entity_user_count: 1,
        number_of_prior_connected_users: 0,
        shared_entity_types_count: 0,
        connected_component_user_count: 1,
        connected_component_total_nodes: 4,
        connected_component_edge_count: 3,
        connected_component_density: 0.50,
      },
    },
    {
      id: 'case_borderline',
      title: 'Borderline Transaction',
      category: 'REVIEW_STEP_UP',
      description: 'New account (<2 days old) placing high value order with promo voucher, warranting 2FA review.',
      expectedDecision: 'REVIEW',
      expectedLevel: 'MEDIUM',
      keySignal: 'New account tenure + high promo usage without graph collusion',
      transaction_id: 'tx_demo_borderline_005',
      features: {
        amount: 135.00,
        product_category: 'beauty',
        is_promo_used: 1,
        hour_of_day: 19,
        day_of_week: 1,
        is_weekend: 0,
        billing_shipping_match: 1,
        account_age_days: 1.8,
        email_domain: 'yahoo.com',
        user_tx_count_1h: 0,
        user_tx_count_24h: 1,
        user_tx_count_7d: 1,
        user_historical_tx_count: 1,
        user_historical_mean_amount: 135.00,
        user_historical_std_amount: 0.0,
        amount_to_user_mean_ratio: 1.0,
        user_promo_rate: 1.0,
        user_unique_device_count: 1,
        user_unique_ip_count: 1,
        user_unique_payment_count: 1,
        user_unique_address_count: 1,
        device_prior_user_count: 1,
        ip_prior_user_count: 1,
        payment_prior_user_count: 1,
        shipping_address_prior_user_count: 1,
        billing_address_prior_user_count: 1,
        max_shared_entity_user_count: 1,
        number_of_prior_connected_users: 1,
        shared_entity_types_count: 0,
        connected_component_user_count: 1,
        connected_component_total_nodes: 4,
        connected_component_edge_count: 3,
        connected_component_density: 0.50,
      },
    },
  ];

  getTransactions(): TransactionListItem[] {
    return this.mockTransactions;
  }

  getTransactionById(id: string): TransactionListItem | undefined {
    return this.mockTransactions.find((t) => t.transaction_id === id);
  }

  getAuditLogs(): AuditRecord[] {
    return this.mockTransactions.map((tx) => ({
      transaction_id: tx.transaction_id,
      timestamp: tx.timestamp,
      risk_score: tx.risk_score,
      risk_level: tx.risk_level,
      decision: tx.decision,
      reason_codes: [tx.primary_reason],
      model_version: 'phase3-v1',
      feature_version: 'features-v2',
      policy_version: 'val-opt-v1',
    }));
  }

  // Network graph topology representation for Cytoscape
  getNetworkGraph(): { nodes: NetworkNode[]; edges: NetworkEdge[] } {
    const nodes: NetworkNode[] = [
      // Ring Cluster (Abuse)
      { id: 'usr_4812', label: 'User 4812 (Abuse)', type: 'USER', isRisk: true, degree: 4, details: { account_age: '0.45d', velocity_24h: 4 } },
      { id: 'usr_4809', label: 'User 4809 (Abuse)', type: 'USER', isRisk: true, degree: 4, details: { account_age: '0.82d', velocity_24h: 3 } },
      { id: 'usr_4815', label: 'User 4815 (Abuse)', type: 'USER', isRisk: true, degree: 3, details: { account_age: '0.21d', velocity_24h: 2 } },
      { id: 'usr_4820', label: 'User 4820 (Abuse)', type: 'USER', isRisk: true, degree: 3, details: { account_age: '0.60d', velocity_24h: 3 } },
      { id: 'dev_sybil_99', label: 'Device: dev_e7a892b', type: 'DEVICE', isRisk: true, degree: 4, details: { prior_users: 7, model: 'Chrome Windows' } },
      { id: 'ip_tor_41', label: 'IP: 194.26.29.11', type: 'IP', isRisk: true, degree: 4, details: { prior_users: 4, asn: 'Hosting / Proxy' } },
      { id: 'pmt_card_77', label: 'Card: •••• 4129', type: 'PAYMENT', isRisk: true, degree: 3, details: { prior_users: 6, card_type: 'Virtual Prepaid' } },
      { id: 'addr_mesh_01', label: 'Addr: Drop Unit 4B', type: 'ADDRESS', isRisk: true, degree: 2, details: { prior_users: 3, postal: '94103' } },

      // Household Cluster (Benign)
      { id: 'usr_hh_alice', label: 'User: Alice (Benign)', type: 'USER', isRisk: false, degree: 2, details: { account_age: '74.5d', velocity_24h: 0 } },
      { id: 'usr_hh_bob', label: 'User: Bob (Benign)', type: 'USER', isRisk: false, degree: 2, details: { account_age: '89.1d', velocity_24h: 0 } },
      { id: 'dev_alice', label: 'Device: iPhone 15', type: 'DEVICE', isRisk: false, degree: 1, details: { prior_users: 1 } },
      { id: 'dev_bob', label: 'Device: MacBook Air', type: 'DEVICE', isRisk: false, degree: 1, details: { prior_users: 1 } },
      { id: 'ip_home_wifi', label: 'IP: 73.189.44.12', type: 'IP', isRisk: false, degree: 2, details: { prior_users: 2, isp: 'Comcast Residential' } },
      { id: 'addr_home', label: 'Addr: 742 Evergreen', type: 'ADDRESS', isRisk: false, degree: 2, details: { prior_users: 2, postal: '97477' } },
    ];

    const edges: NetworkEdge[] = [
      // Ring edges
      { id: 'e1', source: 'usr_4812', target: 'dev_sybil_99', type: 'SHARED_DEVICE' },
      { id: 'e2', source: 'usr_4809', target: 'dev_sybil_99', type: 'SHARED_DEVICE' },
      { id: 'e3', source: 'usr_4815', target: 'dev_sybil_99', type: 'SHARED_DEVICE' },
      { id: 'e4', source: 'usr_4820', target: 'dev_sybil_99', type: 'SHARED_DEVICE' },
      { id: 'e5', source: 'usr_4812', target: 'ip_tor_41', type: 'SHARED_IP' },
      { id: 'e6', source: 'usr_4809', target: 'ip_tor_41', type: 'SHARED_IP' },
      { id: 'e7', source: 'usr_4815', target: 'ip_tor_41', type: 'SHARED_IP' },
      { id: 'e8', source: 'usr_4820', target: 'ip_tor_41', type: 'SHARED_IP' },
      { id: 'e9', source: 'usr_4812', target: 'pmt_card_77', type: 'SHARED_PAYMENT' },
      { id: 'e10', source: 'usr_4809', target: 'pmt_card_77', type: 'SHARED_PAYMENT' },
      { id: 'e11', source: 'usr_4815', target: 'pmt_card_77', type: 'SHARED_PAYMENT' },
      { id: 'e12', source: 'usr_4812', target: 'addr_mesh_01', type: 'SHARED_ADDRESS' },
      { id: 'e13', source: 'usr_4820', target: 'addr_mesh_01', type: 'SHARED_ADDRESS' },

      // Household edges
      { id: 'e14', source: 'usr_hh_alice', target: 'dev_alice', type: 'SHARED_DEVICE' },
      { id: 'e15', source: 'usr_hh_bob', target: 'dev_bob', type: 'SHARED_DEVICE' },
      { id: 'e16', source: 'usr_hh_alice', target: 'ip_home_wifi', type: 'SHARED_IP' },
      { id: 'e17', source: 'usr_hh_bob', target: 'ip_home_wifi', type: 'SHARED_IP' },
      { id: 'e18', source: 'usr_hh_alice', target: 'addr_home', type: 'SHARED_ADDRESS' },
      { id: 'e19', source: 'usr_hh_bob', target: 'addr_home', type: 'SHARED_ADDRESS' },
    ];

    return { nodes, edges };
  }
}
