"""
Data Schemas and Configuration for Abuse-Ring Sentinel.
Defines entity representations, population types, topology classifications, and validation models.
"""

from __future__ import annotations
from enum import Enum
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field


class UserPopulationType(str, Enum):
    """Broad category of a generated user account."""
    BENIGN_ISOLATED = "BENIGN_ISOLATED"
    BENIGN_SHARED = "BENIGN_SHARED"
    ABUSE_RING = "ABUSE_RING"


class RingTopologyType(str, Enum):
    """Graph structure of an abuse ring or benign cluster."""
    NONE = "NONE"
    STAR = "STAR"
    BIPARTITE_MESH = "BIPARTITE_MESH"
    CHAINED_SYBIL = "CHAINED_SYBIL"
    HOUSEHOLD = "HOUSEHOLD"
    SHARED_IP_OFFICE = "SHARED_IP_OFFICE"


class OrderStatus(str, Enum):
    """Lifecycle status of a transaction."""
    COMPLETED = "completed"
    REFUNDED = "refunded"
    CHARGED_BACK = "charged_back"


class ProductCategory(str, Enum):
    """Merchant catalog vertical."""
    ELECTRONICS = "electronics"
    APPAREL = "apparel"
    GIFT_CARDS = "gift_cards"
    DIGITAL_GOODS = "digital_goods"
    GROCERIES = "groceries"


class GeneratorConfig(BaseModel):
    """Configuration parameters for deterministic synthetic data generation."""
    seed: int = Field(default=42, description="Master random seed for reproducibility")
    num_users: int = Field(default=5000, description="Total number of customer accounts to generate")
    start_date: str = Field(default="2026-01-01 00:00:00", description="Earliest transaction window timestamp")
    history_days: int = Field(default=90, description="Duration of history in days")
    
    # Population proportions (must sum to 1.0)
    benign_isolated_ratio: float = Field(default=0.75, description="Fraction of benign isolated users")
    benign_shared_ratio: float = Field(default=0.15, description="Fraction of benign shared-entity users")
    abuse_ring_ratio: float = Field(default=0.10, description="Fraction of coordinated abuse ring users")
    
    # Ring topology distribution within abuse population
    star_ring_ratio: float = Field(default=0.40, description="Fraction of rings using Star topology")
    mesh_ring_ratio: float = Field(default=0.35, description="Fraction of rings using Bipartite Mesh topology")
    chained_ring_ratio: float = Field(default=0.25, description="Fraction of rings using Chained/Sybil topology")
    
    # Output file paths
    output_dir: str = Field(default="data/raw", description="Directory to save generated CSV/Parquet files")


class UserSchema(BaseModel):
    """Schema representing an account entity."""
    user_id: str = Field(description="Unique account identifier (usr_XXXXX)")
    signup_timestamp: str = Field(description="Account creation timestamp ISO-8601")
    email_domain: str = Field(description="Email domain (e.g. gmail.com, tempmail.org)")
    
    # Ground-truth metadata (strictly isolated from model training features)
    user_population_type: UserPopulationType
    is_abuse_ring: int = Field(description="Ground truth binary target: 1 if member of coordinated ring, 0 otherwise")
    ring_id: Optional[str] = Field(default=None, description="Deterministic cluster ID if applicable")
    ring_type: RingTopologyType = Field(default=RingTopologyType.NONE, description="Topology classification")


class TransactionSchema(BaseModel):
    """Schema representing an individual e-commerce transaction."""
    transaction_id: str = Field(description="Unique transaction identifier (tx_XXXXXX)")
    timestamp: str = Field(description="Transaction event timestamp ISO-8601")
    user_id: str = Field(description="Associated customer account identifier")
    amount: float = Field(description="Monetary value in standard currency units")
    currency: str = Field(default="INR", description="Currency ISO code")
    
    # Entity linkage identifiers (Observable by merchant at checkout)
    device_id: str = Field(description="Client device fingerprint hash")
    ip_address: str = Field(description="Client IP address string")
    payment_instrument_id: str = Field(description="Payment token hash (e.g. card/VPA token)")
    shipping_address_id: str = Field(description="Normalized physical shipping address hash")
    billing_address_id: str = Field(description="Normalized billing address hash")
    
    # Behavioral attributes (Observable by merchant)
    product_category: ProductCategory
    is_promo_used: int = Field(default=0, description="1 if discount voucher was applied, 0 otherwise")
    order_status: OrderStatus = Field(default=OrderStatus.COMPLETED, description="Settlement state")
    
    # Ground-truth metadata (MUST BE STRIPPED BEFORE MODEL FEATURE INGESTION)
    is_abuse_ring: int = Field(description="Ground truth label: 1 if generated by an abuse ring, 0 if benign")
    ring_id: Optional[str] = Field(default=None, description="Cluster identifier")
    ring_type: RingTopologyType = Field(default=RingTopologyType.NONE)
    user_population_type: UserPopulationType


class DatasetMetadata(BaseModel):
    """Metadata summary of a generated dataset partition."""
    seed: int
    generated_at: str
    total_users: int
    total_transactions: int
    benign_isolated_users: int
    benign_shared_users: int
    abuse_ring_users: int
    num_abuse_rings: int
    num_benign_groups: int
    abuse_ring_transaction_count: int
    benign_transaction_count: int
    ring_topology_breakdown: Dict[str, int]
    date_range_start: str
    date_range_end: str
