import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-terms',
  standalone: true,
  imports: [CommonModule, RouterLink],
  template: `
    <div class="min-h-screen bg-[#030712] text-slate-100 flex flex-col font-sans selection:bg-cyan-500 selection:text-black">
      <!-- Top Navigation Header -->
      <header class="border-b border-slate-800 bg-[#060A14]/90 backdrop-blur-xl sticky top-0 z-50 py-3.5 px-4 sm:px-8 flex items-center justify-between">
        <a routerLink="/" class="flex items-center gap-3">
          <img src="vigilai_logo.jpg" alt="VigilAI Logo" class="w-8 h-8 rounded-xl object-cover border border-cyan-500/40" />
          <span class="text-base font-extrabold text-white">VigilAI <span class="text-xs text-cyan-400 font-mono font-normal">LEGAL</span></span>
        </a>
        <div class="flex items-center gap-4 text-xs">
          <a routerLink="/privacy" class="text-slate-400 hover:text-cyan-300 transition-colors">Privacy Policy</a>
          <a routerLink="/" class="px-3.5 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 transition-colors">
            ← Return to Home
          </a>
        </div>
      </header>

      <!-- Main Legal Document Body -->
      <main class="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8 space-y-8">
        <div class="border-b border-slate-800 pb-6">
          <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 text-xs font-mono mb-3">
            <span>OFFICIAL LEGAL AGREEMENT</span>
          </div>
          <h1 class="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">Terms of Service</h1>
          <p class="text-xs text-slate-400 mt-2 font-mono">Last Updated: August 26, 2026 | Effective Date: August 26, 2026</p>
        </div>

        <div class="prose prose-invert max-w-none text-slate-300 text-xs leading-relaxed space-y-6">
          <section class="p-6 rounded-2xl bg-[#060A14] border border-slate-800/80 space-y-3">
            <h2 class="text-sm font-bold text-cyan-300 uppercase tracking-wider font-mono">1. Acceptance of Terms</h2>
            <p>
              By accessing, integrating, or utilizing the <strong>VigilAI Autonomous Fraud & Ring Defense Platform</strong> ("Service"), including our REST APIs, webhooks, machine learning inference endpoints, and web management console, you agree to be bound by these Terms of Service ("Terms"). If you are entering into this agreement on behalf of a merchant entity, company, or legal organization, you represent that you possess the requisite authority to bind such entity.
            </p>
          </section>

          <section class="p-6 rounded-2xl bg-[#060A14] border border-slate-800/80 space-y-3">
            <h2 class="text-sm font-bold text-cyan-300 uppercase tracking-wider font-mono">2. Merchant Account & API Key Security</h2>
            <p>
              Merchants are issued cryptographically generated secret API keys (<code class="text-cyan-300 font-mono">ars_live_...</code>) for server-to-server transaction risk evaluation. You are strictly responsible for maintaining the confidentiality of your API keys and authentication credentials. Any API requests signed with your merchant API key will be deemed authorized by your organization.
            </p>
            <ul class="list-disc list-inside space-y-1 text-slate-400 pl-2">
              <li>API keys must never be committed to public code repositories or client-side web bundles.</li>
              <li>Merchant tenants must immediately rotate compromised keys via the VigilAI console or support.</li>
            </ul>
          </section>

          <section class="p-6 rounded-2xl bg-[#060A14] border border-slate-800/80 space-y-3">
            <h2 class="text-sm font-bold text-cyan-300 uppercase tracking-wider font-mono">3. Risk Scoring & Machine Learning SLAs</h2>
            <p>
              VigilAI provides real-time fraud probability scores and automated policy decisions (<code class="text-emerald-400 font-mono">APPROVE</code>, <code class="text-amber-400 font-mono">REVIEW</code>, <code class="text-rose-400 font-mono">BLOCK</code>) generated by our Scikit-Learn Gradient-Boosted Decision Tree model (<strong>Model F</strong>, decision threshold &tau;* = 0.90) and heterogeneous entity collusion graph engine.
            </p>
            <p>
              While VigilAI utilizes point-in-time zero-leakage signals to achieve industry-leading precision, the Service is provided as an automated decision-support system. Merchants maintain ultimate autonomy over fulfillment and transaction settlement decisions.
            </p>
          </section>

          <section class="p-6 rounded-2xl bg-[#060A14] border border-slate-800/80 space-y-3">
            <h2 class="text-sm font-bold text-cyan-300 uppercase tracking-wider font-mono">4. Multi-Tenant Data Isolation & Privacy</h2>
            <p>
              VigilAI enforces strict logical and cryptographic tenant isolation across all transaction records, device fingerprints, and entity collusion graphs. Transaction data submitted by your merchant backend is never exposed to other tenants or shared with third-party advertising networks.
            </p>
          </section>

          <section class="p-6 rounded-2xl bg-[#060A14] border border-slate-800/80 space-y-3">
            <h2 class="text-sm font-bold text-cyan-300 uppercase tracking-wider font-mono">5. Acceptable Use Policy</h2>
            <p>You agree not to:</p>
            <ul class="list-disc list-inside space-y-1 text-slate-400 pl-2">
              <li>Reverse-engineer, decompile, or extract the underlying Scikit-Learn machine learning weights or proprietary graph clustering algorithms.</li>
              <li>Submit deliberately corrupted, toxic, or adversarial payloads intended to induce denial of service.</li>
              <li>Use the risk evaluation service for unlawful surveillance, biometric discrimination, or activities violating consumer financial protection regulations.</li>
            </ul>
          </section>

          <section class="p-6 rounded-2xl bg-[#060A14] border border-slate-800/80 space-y-3">
            <h2 class="text-sm font-bold text-cyan-300 uppercase tracking-wider font-mono">6. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, VigilAI and its creators shall not be liable for any indirect, incidental, punitive, or consequential damages resulting from chargebacks, missed fraudulent transactions, merchant service interruptions, or third-party cloud infrastructure outages.
            </p>
          </section>

          <section class="p-6 rounded-2xl bg-[#060A14] border border-slate-800/80 space-y-3">
            <h2 class="text-sm font-bold text-cyan-300 uppercase tracking-wider font-mono">7. Termination & Inquiries</h2>
            <p>
              Merchants may terminate their account and purge transaction history at any time. For questions regarding these Terms or enterprise compliance inquiries, contact our legal team at <a href="mailto:jeshwar.work@gmail.com" class="text-cyan-300 hover:underline">jeshwar.work&#64;gmail.com</a>.
            </p>
          </section>
        </div>

        <div class="pt-8 border-t border-slate-800 flex items-center justify-between text-xs text-slate-500 font-mono">
          <span>&copy; 2026 VigilAI Inc. All rights reserved.</span>
          <a routerLink="/privacy" class="text-cyan-400 hover:underline">Read Privacy Policy →</a>
        </div>
      </main>
    </div>
  `,
})
export class TermsComponent {}
